name: security-sbom

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Semgrep (default rules)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/default
        # env:
        #   SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  build-and-sbom:
    needs: semgrep
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project (skip if none)
        run: echo "skip build"

      - name: Generate SBOM with Anchore SBOM Action
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json,spdx-json
          output-file: sbom

      - name: List created files (debug)
        run: ls -la sbom* || true

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-files
          path: |
            sbom.cyclonedx.json
            sbom.spdx.json
